/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/payment-result`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/payments` | `/payments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/class/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/club/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/payment-result`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(discover)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(discover)'}/clubs` | `/clubs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(discover)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(discover)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(member)'}/bookings` | `/bookings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(member)'}/classes` | `/classes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(member)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(member)'}/payments` | `/payments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(member)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/class/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/club/[slug]`, params: Router.UnknownOutputParams & { slug: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/payment-result${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(discover)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(discover)'}/clubs${`?${string}` | `#${string}` | ''}` | `/clubs${`?${string}` | `#${string}` | ''}` | `${'/(discover)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(discover)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(member)'}/bookings${`?${string}` | `#${string}` | ''}` | `/bookings${`?${string}` | `#${string}` | ''}` | `${'/(member)'}/classes${`?${string}` | `#${string}` | ''}` | `/classes${`?${string}` | `#${string}` | ''}` | `${'/(member)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(member)'}/payments${`?${string}` | `#${string}` | ''}` | `/payments${`?${string}` | `#${string}` | ''}` | `${'/(member)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/payment-result`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(discover)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/payments` | `/payments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(member)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/class/${Router.SingleRoutePart<T>}` | `/club/${Router.SingleRoutePart<T>}` | { pathname: `/class/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/club/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
    }
  }
}
